name: Scraper
on:
  schedule:
    # https://crontab.guru/#0_*/6_*_*_*
    # runs “At minute 0 past every 6th hour.” take that, github.
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
  push:
    branches:
      - master

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarnCacheDirPath
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run yarn install
        run: yarn install --dev
      - name: Compile Typescript
        run: yarn tsc
      - name: Track the current setup
        run: yarn track
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Update data with latest scrape result
          # branch: tracking-history
